create table users
(
    id           integer generated by default as identity
        constraint users_pkey
            primary key,
    enabled      boolean not null,
    password     varchar(255),
    username     varchar(255),
    authority_id integer
        constraint fkrixikjhjfel192yj7w7xapds7
            references authorities
);

alter table users
    owner to postgres;

create table topics
(
    id        integer generated by default as identity
        constraint topics_pkey
            primary key,
    name      varchar(255),
    status    integer,
    author_id integer
        constraint fk7xkxef4fwbjec06isf4ims4gr
            references users
);

alter table topics
    owner to postgres;

create table posts
(
    id          serial                  not null
        constraint posts_pkey
            primary key,
    name        varchar(2000),
    description text,
    created     timestamp default now() not null,
    creator_id  integer
        constraint fkpbdq30fxpf8l0v3j2eyca7odb
            references users,
    topic_id    integer
        constraint fkrfchr8dax0kfngvvkbteh5n7h
            references topics
);

alter table posts
    owner to postgres;

    create table authorities
(
    id        integer generated by default as identity
        constraint authorities_pkey
            primary key,
    authority varchar(255)
);

alter table authorities
    owner to postgres;